(function(){var n;function r(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function u(a){if(!(a instanceof Array)){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];a=b?b.call(a):{next:r(a)};for(var c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}
var y="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},aa="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function ba(a,b){if(b){var c=aa;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&y(c,a,{configurable:!0,writable:!0,value:b})}}
ba("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,h=0;h<e;h++){var g=d[h];if(b.call(c,g,h,d)){b=g;break a}}b=void 0}return b}});var z=new function(){this.c=[];this.a=[]};function ca(a,b,c,d,e,h){var g=this,m=a.b;this.create=function(){g.b=a.b.g();g.id=d;g.b.attr({"class":"shape",token:g.id});g.children=[];g.A=!1;g.o=!1;g.mask=null;g.maskTill=null;for(var f=0;f<b.i.DOMDocument.Bitmaps.length;f++)if(b.i.DOMDocument.Bitmaps[f].charid==c){var k=a.b.paper.image(b.i.DOMDocument.Bitmaps[f].bitmapPath);g.b.add(k)}f=h.split(",");f=new (Function.prototype.bind.apply(window.Snap.Matrix,[null].concat(u(f))));g.b.transform(f);e&&0!==parseInt(e,10)?(f=A(a,parseInt(e,10)),f.o?f.b.parent().before(g.b):
f.b.before(g.b)):m.add(g.b)};this.create()};function da(a){this.j=[];this.c=[];this.a=[];this.l=[];this.i=a;for(var b=0;b<this.i.DOMDocument.Shape.length;b++)a=this.i.DOMDocument.Shape[b].charid,this.j[a]=this.i.DOMDocument.Shape[b];for(b=0;b<this.i.DOMDocument.Bitmaps.length;b++)a=this.i.DOMDocument.Bitmaps[b].charid,this.a[a]=this.i.DOMDocument.Bitmaps[b];for(b=0;b<this.i.DOMDocument.Text.length;b++)a=this.i.DOMDocument.Text[b].charid,this.l[a]=this.i.DOMDocument.Text[b];if(void 0!==this.i.DOMDocument.Timeline)for(b=0;b<this.i.DOMDocument.Timeline.length-
1;b++)a=this.i.DOMDocument.Timeline[b].charid,this.c[a]=this.i.DOMDocument.Timeline[b]};function ea(a,b,c,d,e,h){var g=a.b;this.a=g;this.b=a.b.g();this.id=d;this.b.attr({"class":"shape",token:this.id});this.children=[];this.o=this.A=!1;this.maskTill=this.mask=null;this.c=b;for(d=0;d<b.i.DOMDocument.Shape.length;d++)if(b.i.DOMDocument.Shape[d].charid==c)for(var m=0;m<b.i.DOMDocument.Shape[d].path.length;m++){var f=d,k=m,l=this.b.path();f=this.c.i.DOMDocument.Shape[f].path[k];l.attr({fill:"transparent",d:f.d});if("Fill"==f.pathType){k=void 0;if(f.color){var p=f.color;p="rgba("+parseInt(p.substring(1,
3),16)+","+parseInt(p.substring(3,5),16)+","+parseInt(p.substring(5,7),16)+","+f.colorOpacity+")";l.attr({fill:p})}if(f.image){p=f.image;var v=new (Function.prototype.bind.apply(window.Snap.Matrix,[null].concat(u(p.patternTransform.split(","))))),t=p.bitmapPath,q=this.a.paper.select("defs pattern image");q?q.attr("href")==t?k=q.parent():k=B(this,t,p,v):k=B(this,t,p,v);l.attr({fill:k})}f.linearGradient&&(k=f.linearGradient,k=E(this,k,"linear"),l.attr({fill:k}));f.radialGradient&&(k=f.radialGradient,
k=E(this,k,"radial",l),l.attr({fill:k}))}else"Stroke"==f.pathType&&f.color&&(k=f.color,l.attr({stroke:"rgba("+parseInt(k.substring(1,3),16)+","+parseInt(k.substring(3,5),16)+","+parseInt(k.substring(5,7),16)+","+f.colorOpacity+")",strokeWidth:f.strokeWidth}))}b=new (Function.prototype.bind.apply(window.Snap.Matrix,[null].concat(u(h.split(",")))));this.b.transform(b);e&&0!==parseInt(e,10)?(a=A(a,parseInt(e,10)),a.o?a.b.parent().before(this.b):a.b.before(this.b)):g.add(this.b)}
function E(a,b,c,d){if("linear"==c){c=parseFloat(b.x2);var e=parseFloat(b.y2);d="L("+(parseFloat(b.x1)+", ")+(parseFloat(b.y1)+", ");d=d+(c+", ")+(e+")")}else{e=d.getBBox().x+d.getBBox().width/2+b.cx/10;var h=d.getBBox().y+d.getBBox().height/2+b.cy/10;c=d.getBBox().x+d.getBBox().width/2+parseFloat(b.fx);var g=d.getBBox().y+d.getBBox().height/2+parseFloat(b.fy);d="R("+(e+", ")+(h+", ");d+=b.r+", ";d+=c+", ";d+=g+")"}for(c=0;c<b.stop.length;c+=1)e=(e=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(b.stop[c].stopColor))?
{r:parseInt(e[1],16),g:parseInt(e[2],16),L:parseInt(e[3],16)}:null,d+="rgba("+e.r+","+e.g+","+e.L+","+b.stop[c].stopOpacity+")",d+=":",d+=b.stop[c].offset,c!==b.stop.length-1&&(d+="-");return a.a.paper.gradient(d)}function B(a,b,c,d){a=a.b.image(b).pattern(0,0,c.width,c.height);a.attr({x:d.e,y:d.f});return a};function fa(a,b,c,d,e,h,g){this.a=a.b;this.bounds=g;this.b=this.a.g();this.id=d;this.b.attr({"class":"text",token:this.id});this.children=[];this.o=this.A=!1;this.maskTill=this.mask=null;for(d=0;d<b.i.DOMDocument.Text.length;d++)if(b.i.DOMDocument.Text[d].charid==c){var m=g=void 0;var f=b.i.DOMDocument.Text[d];var k=this.b.g();this.bounds?g=this.bounds.split(","):g=[0,0,200,100];var l=f.M.Y;var p=f.C[0].S;var v=f.C[0].J[0].style.fontSize;var t=f.C[0].J[0].style.V;var q=f.C[0].J[0].style.U;var C=f.C[0].J[0].style.letterSpacing;
"left"==p?m="start":"center"==p?m="middle":"right"==p&&(m="end");m={"text-anchor":m,"dominant-baseline":"single"==l?"central":"auto","font-family":t,"font-size":v,"letter-spacing":C,fill:q};"false"!==f.M.X&&k.rect(g[0],g[1],g[2],g[3]).attr({stroke:"black",fill:"transparent"});if("single"==l)l=k.text(0,0,f.K),f=parseFloat(g[1])+parseFloat(g[3])/2;else{l=void 0;v=k;k=f;C=m;for(var D=[],w="",ha=parseFloat(g[2]),x=0;-1<x;){w+=k.K.charAt(x);q=v.text(0,0,w);q.attr(C);l=q.getBBox();var L=w.lastIndexOf(" ");
l.w>ha?(t=w.slice(0,L),D.push(t),x=x-(w.length-t.length)+2,w=""):x+=1;x>=k.K.length&&(t=w.slice(0,L),D.push(t),x=-1);q.remove()}q=v.text(0,0,D);q.selectAll("tspan").attr({x:0,dy:l.h+parseFloat(k.C[0].P)});l=q;f=parseFloat(g[1])-2*parseFloat(f.C[0].P)}g="left"==p?parseFloat(g[0]):parseFloat(g[0])+parseFloat(g[2])/2;l.attr(m);l.transform("translate("+g+","+f+")")}b=h.split(",");b=new (Function.prototype.bind.apply(window.Snap.Matrix,[null].concat(u(b))));this.b.transform(b);e&&0!==parseInt(e,10)?(a=
A(a,parseInt(e,10)),a.o?a.b.parent().before(this.b):a.b.before(this.b)):this.a.add(this.b)};function F(a,b,c,d,e,h){this.c=a;this.j=b;this.B=c;this.a=d;this.l=e;this.u=h}F.prototype.m=function(a,b){var c=b.j[this.c],d=b.a[this.c],e=b.l[this.c];if(null!==c&&void 0!==c)b=new ea(a,b,this.c,this.j,this.a,this.l),G(a,b,this.a);else if(null!==d&&void 0!==d)b=new ca(a,b,this.c,this.j,this.a,this.l),G(a,b,this.a);else if(null!==e&&void 0!==e)b=new fa(a,b,this.c,this.j,this.a,this.l,this.u),G(a,b,this.a);else if(c=b.c[this.c])b=new H(c,a,b,this.j,this.B,this.l),G(a,b,this.a),b.play()};
function I(a,b){this.a=a;this.c=b}I.prototype.m=function(a){var b=this.c.split(",");b=new (Function.prototype.bind.apply(window.Snap.Matrix,[null].concat(u(b))));a=A(a,this.a);a.v=b;a.b.transform(b)};function J(){}J.prototype.m=function(){};function K(a){this.a=a}K.prototype.m=function(a){A(a,this.a).b.remove();for(var b=this.a,c=0;c<a.children.length;c+=1)if(a.children[c].id==b){a.children.splice(c,1);break}};function M(a,b){this.a=a;this.c=b}
M.prototype.m=function(a){A(a,this.a).b.attr({visibility:"true"==this.c?"visible":"hidden"})};function N(a,b){this.a=a;this.c=b}N.prototype.m=function(a){var b=A(a,this.a);b.A=!0;b.maskTill=this.c;var c=a.b.mask();c.attr("mask-type","alpha");a=b.b.clone();a.attr({visibility:"visible"});c=c.toDefs();c.append(a);b.I=c;b.b.attr({visibility:"hidden"})};function O(){}
O.prototype.m=function(a){var b,c=!1,d=null,e=null;for(b=0;b<a.children.length;b+=1){var h=a.children[b];if(h.A){c=h.I;d=A(a,h.id);c.clear();d=d.b.clone();d.attr({visibility:"visible"});c.append(d);c=!0;d=h;var g=h.I;e=h.maskTill;var m=a.b.g();m.attr({"class":"maskGroup"});h.b.after(m);m.attr({mask:g});z.c.push(m);a:{var f=g;var k=[m],l=z;for(g=0;g<l.a.length;g+=1)if(l.a[g].b.id==f.id){for(f=0;f<k.length;f+=1)l.a[g].G.push(k[f]);break a}l.a.push({b:f,G:k})}h.id==h.maskTill&&(c=!1)}else c&&(m.prepend(h.b),
h.o=!0,h.mask=d.id,h.id==e&&(c=!1,e=d=null))}};function P(a,b){this.a=a;this.c=b}P.prototype.m=function(a){a=A(a,this.a);var b=this.c.split(",",7);a.b.attr({opacity:parseFloat(b[6])})};function Q(a,b){this.a=a;this.c=b}Q.prototype.m=function(a){a.F[this.a]=this.c};function R(a){this.a=a}R.prototype.m=function(a){delete a.F[this.a]};function S(){}S.prototype.m=function(){};function H(a,b,c,d,e,h){b="svg"==b.type?b:b.b;d&&(this.id=d);e&&(this.name=e);this.b=b.g();this.b.attr({"class":"movieclip",token:this.id});this.transform=h;this.l=a;this.c=0;this.B=this.l.frameCount;this.F={};this.u=[];this.children=[];this.o=this.A=!1;this.maskTill=this.I=this.mask=null;this.j=!0;this.R=c;this.a=[];this.v=new window.Snap.Matrix;this.l.Label&&(this.u=this.l.Label);this.transform&&(this.v=new (Function.prototype.bind.apply(window.Snap.Matrix,[null].concat(u(this.transform.split(","))))),
this.b.transform(this.v))}n=H.prototype;n.addChild=function(a,b){G(this,a,b?b:0)};function A(a,b){return a.children.find(function(c){return c.id==b})}function G(a,b,c){b.name&&(a[b.name]=b);if(c&&0!==parseInt(c,10)){var d=A(a,parseInt(c,10));d.o?d.b.parent().before(b.b):d.b.before(b.b)}else a.b.add(b.b);0===parseInt(c,10)&&a.children.unshift(b);for(d=0;d<a.children.length;d+=1)if(a.children[d].id==c){a.children.splice(d+1,0,b);break}}n.N=function(){return this.children.some(function(a){return a.A})};
n.getX=function(){var a=0;this.v&&(a=this.v.x());return a};n.getY=function(){var a=0;this.v&&(a=this.v.y());return a};n.mouseover=function(a){this.b.mouseover(a)};n.mouseout=function(a){this.b.mouseout(a)};n.mousedown=function(a){this.b.mousedown(a)};n.mousemove=function(a){this.b.mousemove(a)};n.click=function(a){this.b.click(a)};n.O=function(a){eval("(function () {"+a+"}).call(this);")};function T(a,b){return a.l.Frame.find(function(c){return c.num==b})}
function U(a){var b,c;a.c=0;if(b=T(a,a.c))for(b=b.Command,c=0;c<a.children.length;c+=1){var d=!1;for(var e=a.children[c],h=0;h<b.length;++h){var g=b[h];var m=g.cmdType;if("Place"==m&&parseInt(e.id,10)==parseInt(g.objectId,10)){d=!0;break}}!1===d&&a.a.push(new K(e.id))}else for(b=0;b<a.children.length;b+=1)c=a.children[b],c=new K(c.id),a.a.push(c)}
n.D=function(){var a;!1!==this.j&&(this.H(),V(this));for(a=0;a<this.children.length;a+=1)this.children[a].D&&this.children[a].D();for(a=z.c.length-1;-1<a;--a){var b=z.c[a];0===b.children().length&&(b.remove(),z.c.splice(a,1))}var c;for(a=z.a.length-1;-1<a;--a){var d=z.a[a];for(b=c=0;b<d.G.length;b+=1)d.G[b].Z&&(c+=1),c==d.G.length&&(d.b.remove(),z.a.splice(a,1))}};
function W(a,b){for(var c,d=0;d<b.length;d+=1){c=b[d];var e;switch(c.cmdType){case "Place":(e=A(a,c.objectId))?(c=new I(c.objectId,c.transformMatrix),a.a.push(c),c=new J,a.a.push(c)):(c=new F(c.charid,c.objectId,c.name,c.placeAfter,c.transformMatrix,c.bounds),a.a.push(c));break;case "Move":c=new I(c.objectId,c.transformMatrix);a.a.push(c);break;case "Remove":c=new K(c.objectId);a.a.push(c);break;case "UpdateZOrder":c=new J;a.a.push(c);break;case "UpdateVisibility":c=new M(c.objectId,c.visibility);
a.a.push(c);break;case "UpdateColorTransform":c=new P(c.objectId,c.colorMatrix);a.a.push(c);break;case "UpdateMask":c=new N(c.objectId,c.maskTill);a.a.push(c);break;case "AddFrameScript":c=new Q(c.scriptId,c.script);a.a.push(c);break;case "RemoveFrameScript":c=new R(c.scriptId);a.a.push(c);break;case "SetFrameLabel":c=new S,a.a.push(c)}}a.N&&(c=new O,a.a.push(c));b=a.a;d=a.R;for(c=0;c<b.length;c++)void 0!==b[c]&&b[c].m(a,d)}
n.H=function(){if(this.j){this.a=[];this.c==this.B&&U(this);var a=T(this,this.c);this.c++;a&&W(this,a.Command)}};function V(a){for(var b in a.F)a.O.call(a,a.F[b])}n.play=function(){this.j=!0};n.stop=function(){this.j=!1};n.gotoAndStop=function(a){X(this,a,!0)};n.gotoAndPlay=function(a){X(this,a,!1)};
function X(a,b,c){if("string"===typeof b){for(var d=a.u,e=!1,h=d.length-1;0<=h;h--)if(b===d[h].name){b=parseInt(d[h].W,10)+1;e=!0;break}if(!1===e)return}if(!(1>b||b>a.B))if(b==a.c)!1===c?a.play():a.stop();else{a.play();b<a.c&&(a.a=[],U(a),a.c=0,(d=T(a,a.c))&&W(a,d.Command));for(;a.c<b;)for(a.H(),d=0;d<a.children.length;d+=1)a.children[d].H&&a.children[d].H();!1===c?a.play():a.stop();V(a)}}n.log=function(){-1<this.id.indexOf("svg")&&Array.prototype.slice.call(arguments).unshift(this.id.toUpperCase())};function Y(a,b,c,d,e){b=void 0===b?100:b;c=void 0===c?100:c;e=void 0===e?{}:e;this.u=void 0===d?24:d;this.j=null;this.data=a;this.version="1.2.3";var h=e;d=h.T;e=h.element;this.c=h=void 0===h.autoplay?!0:h.autoplay;this.l=new da(a);a=e?new window.Snap(e):d?new window.Snap(d):new window.Snap(b,c);a.attr({id:a.id});a.attr({viewBox:"0 0 "+b+" "+c,preserveAspectRatio:"xMidYMid meet"});this.s=a;this.id=a.id;d&&a.attr({width:b,height:c});this.a=null;this.create(a);h?(this.a.play(),this.c=!0):Z(this);this.B=
{}}Y.prototype.toString=function(){return"Snap.svg Animator v"+this.version};Y.prototype.create=function(a){for(var b=this,c,d=this.data.DOMDocument.Timeline.length-1;-1<d;--d)if(this.data.DOMDocument.Timeline[d].linkageName)this.B[this.data.DOMDocument.Timeline[d].linkageName]=this.data.DOMDocument.Timeline[d];else{c=d;break}this.a=new H(this.l.i.DOMDocument.Timeline[c],a,this.l,this.id);this.j=setTimeout(function(){Z(b)},1E3/this.u)};
Y.prototype.stop=function(){0==this.a.c&&this.a.D();this.a.stop();this.c=!1};function Z(a){a.c&&a.a.D();clearTimeout(a.j);a.j=setTimeout(function(){Z(a)},1E3/a.u)};window.SVGAnim=Y;}).call(this);

//# sourceMappingURL=svg-anim.js.map