export default {
  title: 'Inside UK\'s Technocracy And Mafia Behind It',
  seo: 'Democracy and capitalism are incompatible: money always talks. Learn who is UK\'s plutocracy and how they are robbing population with Industrial Strategy.',
  topics: ['UK', 'politics'],
  // focus: true,
}

export const links = {
  ad: 'https://art-deco.github.io/license/',
  'ref-forbes': 'https://www.forbes.com/profile/eileen-burbidge/',
  'wired': 'https://www.youtube.com/watch?v=swIoyaBUpEg',
  'ch-tn': 'https://beta.companieshouse.gov.uk/company/08843778/officers',
  'ch-tn-wm': 'https://web.archive.org/save/https://beta.companieshouse.gov.uk/company/08843778/officers',
  'ch-public': 'https://beta.companieshouse.gov.uk/company/10608507/filing-history',
  'wiki-propaganda': 'https://en.wikipedia.org/wiki/Propaganda:_The_Formation_of_Men%27s_Attitudes',
  'wework': 'https://www.youtube.com/watch?v=X2LwIiKhczo',
  'bcs': 'https://www.bcs.org/get-qualified/become-chartered/chartered-it-professional/',
  'korski-photo': 'https://www.pressreader.com/uk/scottish-daily-mail/20170328/281715499449399',
  'crunch-echo': 'https://www.crunchbase.com/funding_round/echo-8-seed--730e481c#section-overview',
  'tis': 'https://www.timesofisrael.com/britain-appoints-special-technology-ambassador-to-israel/',
  'nhs': 'https://healthtech.blog.gov.uk/2019/06/24/nhsx-giving-patients-and-staff-the-technology-they-need/',
  'tan': 'https://www.youtube.com/watch?v=7REeejwQ5Tc',
  'siege': 'http://www.ejiltalk.org/is-gaza-still-occupied-by-israel/',
  'zionism': 'https://www.nkusa.org/AboutUs/Zionism/judaism_isnot_zionism.cfm',
  'pizza': 'https://www.haaretz.com/opinion/.premium-jews-and-capitalism-call-them-frenemies-1.5455400',
  torah: 'https://torah.org/torah-portion/rabbiwein-5766-shoftim/',
  'corrupt-leadership': 'https://www.myjewishlearning.com/article/corrupt-leadership/',
  bribery: 'https://www.jewishvirtuallibrary.org/bribery',
  wood: 'http://choppingwood.blogspot.com/2011/09/hasagat-gvul-message-for-each-of-us.html',
  hassagat: 'https://www.jewishvirtuallibrary.org/hassagat-gevul',
  'ef-history': 'https://medium.com/entrepreneur-first/entrepreneur-first-has-built-over-120-companies-so-who-built-ef-9ab067babab6',
  te: 'https://tradingeconomics.com/united-kingdom/gdp-growth',
  gps: 'https://www.medscape.com/slideshow/2019-uk-doctors-salary-report-6011623#8',
  'alice-mat': 'https://www.youtube.com/watch?v=hJQr_h51dtg',
  'al-jazeera': 'https://www.youtube.com/watch?v=ceCOhdgRBoc',
  stats: 'https://www.ons.gov.uk/aboutus/transparencyandgovernance/freedomofinformationfoi/muslimpopulationintheuk/',
  huddle: 'https://www.businessinsider.com/tech-city-not-needed-says-huddle-founder-2015-10',
  'king-david': 'https://en.wikipedia.org/wiki/King_David_Hotel_bombing',
  'network': 'https://www.theguardian.com/business/2019/may/02/railway-arches-sold-off-with-no-thought-for-tenants-says-watchdog',
}